remote_theme: pages-themes/tactile@v0.2.0 #pages-themes/midnight@v0.2.0 #pages-themes/minimal@v0.2.0

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Mark Paral

baseurl: ""

google_analytics: 

description:

collections:
  projects:
    output: true
    permalink: /projects/:title/
  publications:
    output: false